Sequel.migration do
  up do
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 703;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 361;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 786;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 579;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 565;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 564;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 338;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 436;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 637;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 340;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 343;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 691;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 685;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 684;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 439;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 939;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 425;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 419;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 757;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 690;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 912;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 332;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 633;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 363;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 686;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 258;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 549;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 267;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 266;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 311;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 857;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 915;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 780;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 210;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 736;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 366;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 808;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 647;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 346;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 378;'
run 'UPDATE products set ideal_stock = 0 WHERE p_id = 313;'

  end

  down do
  end
end
